defmodule PhxTesteWeb.Components.Hero do
  @moduledoc """
  A sample component generated by `mix surface.init`.
  """
  use Surface.Component

  import PhxTesteWeb.Gettext

  @doc "The name"
  prop name, :string, default: "Guest"

  @doc "The subtitle"
  prop subtitle, :string

  @doc "The color"
  prop color, :string, values!: ["danger", "info", "warning"]

  def render(assigns) do
    ~F"""
    <section class={"phx-hero", "alert-#{@color}": @color}>
      <h1> Membros da Linha 18 </h1>

    <div class="ui horizontal list">
      <div class="item">
        <img class="ui mini circular image" src="/assets/images/pescartelogo.png">
        <div class="content">
          <div class="ui header">Geraldo Timoteo</div>
          Coordenador Geral
        </div>
      </div>

      <div class="item">
        <img class="ui mini circular image" src="/images/avatar2/small/elyse.png">
        <div class="content">
          <div class="ui header">Zoey Pessanha</div>
          Desenvolvedor
        </div>
      </div>

      <div class="item">
        <h2 class="ui header">
          <img class="ui medium circular image" src="/images/avatar/flor1.jpg">
        </h2>
        <div class="content">
          <div class="ui header">Sahudy Montenegro</div>
          Desenvolvedor
        </div>
      </div>

      <div class="item">
        <h2 class="ui header">
          <img src="/images/avatar/Anna-Perfil.png" class="ui circular image center">
        </h2>
        <div class="content">
          <div class="ui header">
           <a href="http://lattes.cnpq.br/7484786835288826">Annabell Tamariz</a>
          </div>
          Desenvolvedor
        </div>
      </div>
    </div>

<h2 class="ui header">
      <img class="ui large circular image" src="/images/avatar/Anna-Perfil.png">
    </h2>
</section>
    """
  end
end
# ui logo v-align centered image one wide column"
# para definir a equipe, usamos ui horizontal list"
